{{- if and .Values.global.ingress.enabled .Values.global.ingress.tls.enabled .Values.certManager.clusterIssuerName }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.global.ingress.tls.secretName }}
  namespace: {{ include "iam.ns" . }}
spec:
  secretName: {{ .Values.global.ingress.tls.secretName }}
  dnsNames:
    - {{ include "iam.webHost" . | quote }}
  issuerRef:
    name: {{ .Values.certManager.clusterIssuerName }}
    kind: ClusterIssuer
{{- end }}