{{- if .Values.postgres.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-postgres
  namespace: {{ include "iam.ns" . }}
  labels:
    app: keycloak-postgres
    {{- include "iam.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak-postgres
  template:
    metadata:
      labels:
        app: keycloak-postgres
    spec:
      containers:
        - name: db
          image: {{ .Values.postgres.image }}
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef: { name: keycloak-postgres-secret }
          env:
            - name: POSTGRES_DB
              value: postgres
          resources:
{{- merge .Values.resourcesDefaults (dict) | toYaml | nindent 12 }}
          readinessProbe:
            exec: { command: ["sh","-c","pg_isready -U ${POSTGRES_USER} -d postgres"] }
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            exec: { command: ["sh","-c","pg_isready -U ${POSTGRES_USER} -d postgres"] }
            initialDelaySeconds: 30
            periodSeconds: 10
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: keycloak-pgdata
{{- end }}
---
{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-pgdata
  namespace: {{ include "iam.ns" . }}
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: {{ .Values.postgres.persistence.size }}
  {{- if .Values.postgres.persistence.storageClassName }}
  storageClassName: {{ .Values.postgres.persistence.storageClassName }}
  {{- end }}
{{- end }}
---
{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: keycloak-postgres
  namespace: {{ include "iam.ns" . }}
  labels:
    app: keycloak-postgres
    {{- include "iam.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: keycloak-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
{{- end }}
---
{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-postgres-secret
  namespace: {{ include "iam.ns" . }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.postgres.admin.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.admin.password | quote }}
{{- end }}