{{- if .Values.certManager.createClusterIssuer }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.certManager.clusterIssuerName }}
spec:
  acme:
    email: {{ .Values.certManager.email | quote }}
    server: {{ .Values.certManager.server | quote }} # prod or staging
    privateKeySecretRef:
      name: {{ .Values.certManager.accountKeySecret | quote }}
    solvers:
      - http01:
          ingress:
            class: {{ .Values.global.ingress.className | default "traefik" }}
{{- end }}
