{{- if .Values.orchestrator.common.crypto.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.orchestrator.common.crypto.secretName }}
  namespace: {{ include "hauth.ns" . }}
  labels:
    {{- include "hauth.labels" . | nindent 4 }}
type: Opaque
stringData:
  pubKey.pem: |
{{ .Values.orchestrator.common.crypto.publicKey | nindent 4 }}
  privKey.pem: |
{{ .Values.orchestrator.common.crypto.privateKey | nindent 4 }}
  service-account.json: |
{{- if .Values.orchestrator.common.crypto.firebaseServiceAccount }}
{{ .Values.orchestrator.common.crypto.firebaseServiceAccount | nindent 4 }}
{{- else }}
{{ "{}" | nindent 4 }}
{{- end }}
{{- if .Values.orchestrator.common.crypto.privateKeyPassword }}
  privateKeyPassword: "{{ .Values.orchestrator.common.crypto.privateKeyPassword }}"
{{- end }}
{{- end }}
