{{- if .Values.core.postgres.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: {{ include "hauth.ns" . }}
  labels:
    {{- include "hauth.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.core.postgres.admin.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.core.postgres.admin.password | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-initdb
  namespace: {{ include "hauth.ns" . }}

data:
  01-init.sql: |
{{- .Values.core.postgres.initSql | nindent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: {{ include "hauth.ns" . }}
  labels:
    app: postgres
    {{- include "hauth.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: db
          image: {{ .Values.core.postgres.image }}
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: postgres-secret
          env:
            - name: POSTGRES_DB
              value: {{ .Values.core.postgres.db.name | quote }}
          resources:
{{- merge .Values.resourcesDefaults (.Values.core.postgres.resources | default dict) | toYaml | nindent 12 }}
          readinessProbe:
            exec:
              command: ["sh","-c","pg_isready -U ${POSTGRES_USER} -d postgres"]
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            exec:
              command: ["sh","-c","pg_isready -U ${POSTGRES_USER} -d postgres"]
            initialDelaySeconds: 30
            periodSeconds: 10
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
            - name: initdb
              mountPath: /docker-entrypoint-initdb.d
              readOnly: true
      volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: pgdata
        - name: initdb
          configMap:
            name: postgres-initdb
            items:
              - key: 01-init.sql
                path: 01-init.sql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgdata
  namespace: {{ include "hauth.ns" . }}
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: {{ .Values.core.postgres.persistence.size }}
  {{- if .Values.core.postgres.persistence.storageClassName }}
  storageClassName: {{ .Values.core.postgres.persistence.storageClassName }}
  {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: {{ include "hauth.ns" . }}
  labels:
    app: postgres
    {{- include "hauth.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
{{- end }}