{{- if .Values.core.redis.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: {{ include "hauth.ns" . }}
  labels:
    app: redis
    {{- include "hauth.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: {{ .Values.core.redis.image }}
          args: ["redis-server","--appendonly","yes","--maxmemory","256mb","--maxmemory-policy","allkeys-lru"]
          ports:
            - containerPort: 6379
          resources:
{{- merge .Values.resourcesDefaults (.Values.core.redis.resources | default dict) | toYaml | nindent 12 }}
          readinessProbe:
            tcpSocket: { port: 6379 }
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            tcpSocket: { port: 6379 }
            initialDelaySeconds: 15
            periodSeconds: 10
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: redis-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
  namespace: {{ include "hauth.ns" . }}
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: {{ .Values.core.redis.persistence.size }}
  {{- if .Values.core.redis.persistence.storageClassName }}
  storageClassName: {{ .Values.core.redis.persistence.storageClassName }}
  {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: {{ include "hauth.ns" . }}
  labels:
    app: redis
    {{- include "hauth.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
{{- end }}