{{- $v := .Values -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ required "values.name is required" $v.name }}
  {{- with $v.namespace }}
  namespace: {{ . }}
  {{- end }}
type: {{ $v.type | default "Opaque" }}
{{- with $v.dataB64 }}
data:
{{ toYaml . | nindent 2 }}
{{- end }}
{{- with $v.stringData }}
stringData:
{{- range $k, $val := . }}
  {{- if (contains "\n" ($val | toString)) }}
  {{ $k | quote }}: |-
{{- $val | nindent 4 }}
  {{- else }}
  {{ $k | quote }}: {{ $val | quote }}
  {{- end }}
{{- end }}
{{- end }}
