{{- if .Values.init.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgres.fullname" . }}-initdb
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
data:
  01-init.sql: |
{{- include "postgres.defaultInitSql" . | nindent 4 }}
{{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "postgres.fullname" . }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "postgres.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "postgres.fullname" . }}
        {{- include "postgres.labels" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      containers:
        - name: db
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort  }}
          env:
            - name: POSTGRES_DB
              value: {{ .Values.db.name | quote }}
            {{- if .Values.env }}
              {{- if kindIs "map" .Values.env }}
                {{- range $k, $v := .Values.env }}
            - name: {{ $k }}
              value: {{ $v | quote }}
                {{- end }}
              {{- else }}
                {{- toYaml .Values.env | nindent 12 }}
              {{- end }}
            {{- end }}
            {{- if .Values.secretEnv }}
              {{- $defaultSecret := (include "postgres.fullname" .) -}}
              {{- if and (hasKey .Values "secret") (kindIs "map" .Values.secret) (hasKey .Values.secret "name") -}}
                {{- $defaultSecret = default $defaultSecret .Values.secret.name -}}
              {{- else if and (hasKey .Values "secret") (kindIs "string" .Values.secret) -}}
                {{- $defaultSecret = .Values.secret -}}
              {{- end }}
              {{- range $name, $ref := .Values.secretEnv }}
            - name: {{ $name }}
              valueFrom:
                secretKeyRef:
                  {{- if kindIs "map" $ref }}
                  name: {{ $ref.name }}
                  key: {{ $ref.key }}
                  {{- else }}
                  name: {{ $defaultSecret }}
                  key: {{ $ref }}
                  {{- end }}
              {{- end }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          readinessProbe:
            exec:
              command: ["sh","-c","pg_isready -U ${POSTGRES_USER} -d postgres"]
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          livenessProbe:
            exec:
              command: ["sh","-c","pg_isready -U ${POSTGRES_USER} -d postgres"]
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
            {{- if .Values.init.enabled }}
            - name: initdb
              mountPath: /docker-entrypoint-initdb.d
              readOnly: true
            {{- end }}
      volumes:
        - name: pgdata
          {{- if .Values.persistence.existingClaim }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | quote }}
          {{- else }}
          persistentVolumeClaim:
            claimName: pgdata
          {{- end }}
        {{- if .Values.init.enabled }}
        - name: initdb
          configMap:
            name: {{ include "postgres.fullname" . }}-initdb
        {{- end }}
---
{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgdata
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  {{- if .Values.persistence.storageClassName }}
  storageClassName: {{ .Values.persistence.storageClassName | quote }}
  {{- end }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgres.fullname" . }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "postgres.fullname" . }}
  ports:
    - name: postgres
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
